# Generated by Django 4.1.1 on 2022-09-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=100, verbose_name='Patente')),
                ('cliente', models.CharField(max_length=100, verbose_name='Nombre')),
                ('vehiculo', models.CharField(max_length=100, verbose_name='Vehiculo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('description', models.TextField(null=True, verbose_name='Descripcion')),
            ],
        ),
    ]
