# Generated by Django 4.1.1 on 2022-09-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moto',
            old_name='description',
            new_name='descripcion',
        ),
    ]
