# Generated by Django 4.1.1 on 2022-10-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_remove_moto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='cliente',
            field=models.CharField(max_length=100, verbose_name='Cliente'),
        ),
    ]
