# Generated by Django 4.1.1 on 2022-10-31 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_alter_moto_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='imagen',
        ),
    ]
